#!/usr/bin/env ruby

require 'webrick'

require_relative '../lib/renderer'

renderer = Renderer.new
server = WEBrick::HTTPServer.new(Port: 8000)
server.mount_proc '/' do |_req, res|
  res.body = renderer.render
end
server.start
